services:
  processor-postgres:
    image: postgres:14-alpine
    container_name: starterkit-processor-postgres
    profiles:
      - processor-db
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $PROCESSOR_POSTGRES_USER -d $PROCESSOR_POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/processor/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PROCESSOR_POSTGRES_PASSWORD}
      - POSTGRES_USER=${PROCESSOR_POSTGRES_USER}
      - POSTGRES_DB=${PROCESSOR_POSTGRES_DB}
    networks:
      - processor-db-net
    restart: unless-stopped

networks:
  processor-db-net: